name: StudioGraphene SAST Analytics

on:
  workflow_call:
    inputs:
      PULSE_URL:
        type: string
        default: "https://a0lrn1xwl4.execute-api.eu-west-1.amazonaws.com"
      semgrep_options:
        type: string
        default: ""
      sast_report_pulse_before_step_command:
        type: string
        default: ""
      sast_report_pulse_after_step_command:
        type: string
        default: ""

jobs:
  sast_analytics:
    uses: studiographene/github-action-workflows/.github/workflows/pulse-sast-analytics.yml@feature/nodejs-ci # if you want alternatively pin to tag version version
    secrets: inherit
    with:
      PULSE_URL: ${{ inputs.PULSE_URL }}
      semgrep_options: ${{ inputs.semgrep_options }}
      before_step_command: ${{ inputs.sast_report_pulse_before_step_command }}
      after_step_command: ${{ inputs.sast_report_pulse_after_step_command }}

